name: publish

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-*.*'

jobs:
  publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
      - run: curl -fsSL 'https://services.gradle.org/distributions/gradle-8.5-bin.zip' -o 'gradle.zip'
      - run: unzip gradle.zip
      - run: mv gradle* /opt
      - run: echo "/opt/gradle/bin" >> "$GITHUB_PATH"
      - run: gradle --help
      - run: gradle wrapper
      - run: ./gradlew publish
        env:
          VERSION: ${{ github.ref_name }}
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
